"""crear tabla pending_operations

Revision ID: aee5b5e6aa34
Revises: c7d77b38f940
Create Date: 2026-09-15 20:11:28.472838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aee5b5e6aa34'
down_revision: Union[str, Sequence[str], None] = 'c7d77b38f940'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('operation_uuid', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('cash_register_id', sa.Integer(), nullable=False),
    sa.Column('payload', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['cash_register_id'], ['cash_registers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operation_uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pending_operations')
    # ### end Alembic commands ###
